name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e565ff8193350b6669a6e8e8138976e6d58a8e6d91de02fe15d6192033bdb26d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
