name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b3b0f89fb5a9d514acecf9fc4009705c0fa5636a3c20261d62ff306eba944be"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
