name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f043bd00f94f0d9c3fede5069974efe3dc0789502599d066c6454234cc2d5f1d"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
