name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b8b7b5d640737903dfbe8528946206c0167d5e89a317636512e79ea62b123c8"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
