name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f01528fa5d8069c46a3694ed6683684de30f3b9a37e958730d72312d5caee3b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
