name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7a4547213ef882c07a1acf009140c715c3b6daa5e52b1637dd47def0547d256"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
