name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edca67914449794976900099bcf4227d237946c8e1117d2fe9407e6375fd6ab4"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
