name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "030c6b95206ac962763379c1db2558fb8fbf24e2c12be5d72b6b2fa22275712a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
