name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d41256bb6e4d875c0f54c708a8c4f7658c2363be6c3fe13ddbe08c888c0dc87e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
