name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fd575b4e7ebe2521d5f49d9419d4b7940e465378db4520e946725400c56e50b"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
