name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0acdcb28457eac630561fb416b413e82d759f1d77f45b9a6deaa49dce25dfb43"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
