name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "382467b0203afb6fa4b9d0968175a3e6345fca3d7011accadfb34f6f22ebf5fc"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
