name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5382da2781bc2ddeb0c79ed0482cc1f8c04de0dfcfa78feeef6e98346e54a8f0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
