name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9bed0e68b82e4d705b4b8b77df7e917275a3047a724926701106fcf1e08afa0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
