name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a8fe049e160a458746949aa63e57c62cbf568e5869aad6bfef28a8bfe141947"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
