name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "496774543447b286efb01064282b3cc0b59a947c017367472804bf83bff0cd51"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
