name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "833fbecba01adcc6020a0ebafce466ab77243309e317ee7f47381b2dba7b5313"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
