name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "888a3a88f38aedd092c02db1ed89554aa62d5181bffd698504556c15ad5de38b"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
