name = "ToyVo_Project_Oasis_3"
author = "ToyVo + originals"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d113a02dd4fc90c776f1e9bd91b2adc5cf12ac5ea18b84ec99b8140bb11e5bec"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
