name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d1598e42059996b8a7f6a34f8270df2f81e745147bd11750a716e4f1ee6d751"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
