name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5ac61a4ea3ba27514132128f1bb791e74dec10576c06080f7ad0d0f3dfda909"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
