name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14aefcd3baac9bfbf102a62289913aa329be611b024f27c4dffa0599e90507ba"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
