name = "nixmc"
author = "Toy_Vo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e36b336cb1f5fd3841e53707bc544e4b09f447f263ec68736650b5d1b03f7bb"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
