#packmode mythic
mods.extendedcrafting.TableCrafting.addShaped(0, <contenttweaker:caz_metal>, [
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:jes_metal>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:got_metal>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:sin_metal>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>], 
	[<contenttweaker:klein_star_6_inert>, <contenttweaker:klein_star_6_inert>, <contenttweaker:klein_star_6_inert>, <contenttweaker:chaos_ingot>, <contenttweaker:chaos_ingot>, <contenttweaker:chaos_ingot>, <contenttweaker:klein_star_6_inert>, <contenttweaker:klein_star_6_inert>, <contenttweaker:klein_star_6_inert>], 
	[<contenttweaker:klein_star_6_inert>, <contenttweaker:tex_plate>, <contenttweaker:klein_star_6_inert>, <contenttweaker:chaos_ingot>, <contenttweaker:dad_plate>, <contenttweaker:chaos_ingot>, <contenttweaker:klein_star_6_inert>, <contenttweaker:slo_plate>, <contenttweaker:klein_star_6_inert>], 
	[<contenttweaker:klein_star_6_inert>, <contenttweaker:klein_star_6_inert>, <contenttweaker:klein_star_6_inert>, <contenttweaker:chaos_ingot>, <contenttweaker:chaos_ingot>, <contenttweaker:chaos_ingot>, <contenttweaker:klein_star_6_inert>, <contenttweaker:klein_star_6_inert>, <contenttweaker:klein_star_6_inert>], 
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:wilx_gear>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:brae_gear>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:chach_gear>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>]]);

	mods.extendedcrafting.TableCrafting.addShaped(0, <contenttweaker:sey_metal>, [
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:car_metal>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:lv_metal>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:kev_metal>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>], 
	[<contenttweaker:ogasexy_block>, <contenttweaker:ogasexy_block>, <contenttweaker:ogasexy_block>, <botania:brewvial>.withTag({brewKey: "nightVision"}), <botania:brewvial>.withTag({brewKey: "nightVision"}), <botania:brewvial>.withTag({brewKey: "nightVision"}), <contenttweaker:ogasexy_block>, <contenttweaker:ogasexy_block>, <contenttweaker:ogasexy_block>], 
	[<contenttweaker:ogasexy_block>, <contenttweaker:maci_gear>, <contenttweaker:ogasexy_block>, <botania:brewvial>.withTag({brewKey: "nightVision"}), <contenttweaker:kiki_gear>, <botania:brewvial>.withTag({brewKey: "nightVision"}), <contenttweaker:ogasexy_block>, <contenttweaker:kire_gear>, <contenttweaker:ogasexy_block>], 
	[<contenttweaker:ogasexy_block>, <contenttweaker:ogasexy_block>, <contenttweaker:ogasexy_block>, <botania:brewvial>.withTag({brewKey: "nightVision"}), <botania:brewvial>.withTag({brewKey: "nightVision"}), <botania:brewvial>.withTag({brewKey: "nightVision"}), <contenttweaker:ogasexy_block>, <contenttweaker:ogasexy_block>, <contenttweaker:ogasexy_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:ske_plate>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:ren_plate>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:dea_plate>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>]]);

	mods.extendedcrafting.TableCrafting.addShaped(0, <contenttweaker:bear_metal>, [
	[<openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>], 
	[<openmodularturrets:ammo_meta:1>, <contenttweaker:jak_metal>, <openmodularturrets:ammo_meta:1>, <contenttweaker:prism_block>, <contenttweaker:mis_metal>, <contenttweaker:prism_block>, <openmodularturrets:ammo_meta:1>, <contenttweaker:ann_metal>, <openmodularturrets:ammo_meta:1>], 
	[<openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>], 
	[<contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <openblocks:beartrap>, <openblocks:beartrap>, <openblocks:beartrap>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>], 
	[<contenttweaker:infinite_chaos>, <contenttweaker:hep_plate>, <contenttweaker:infinite_chaos>, <openblocks:beartrap>, <contenttweaker:mem_plate>, <openblocks:beartrap>, <contenttweaker:infinite_chaos>, <contenttweaker:dat_plate>, <contenttweaker:infinite_chaos>], 
	[<contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <openblocks:beartrap>, <openblocks:beartrap>, <openblocks:beartrap>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>], 
	[<openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>], 
	[<openmodularturrets:ammo_meta:1>, <contenttweaker:fatp_gear>, <openmodularturrets:ammo_meta:1>, <contenttweaker:prism_block>, <contenttweaker:yzul_gear>, <contenttweaker:prism_block>, <openmodularturrets:ammo_meta:1>, <contenttweaker:jack_gear>, <openmodularturrets:ammo_meta:1>], 
	[<openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>, <openmodularturrets:ammo_meta:1>]]);

	mods.extendedcrafting.TableCrafting.addShaped(0, <contenttweaker:og_metal>, [
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <ore:oc:materialALU>, <ore:oc:materialALU>, <ore:oc:materialALU>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:myt_metal>, <contenttweaker:prism_block>, <ore:oc:materialALU>, <contenttweaker:hyp_metal>, <ore:oc:materialALU>, <contenttweaker:prism_block>, <contenttweaker:edd_metal>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <ore:oc:materialALU>, <ore:oc:materialALU>, <ore:oc:materialALU>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>], 
	[<contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:rak_coin>, <contenttweaker:rak_coin>, <contenttweaker:rak_coin>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>], 
	[<contenttweaker:infinite_chaos>, <contenttweaker:mldeg_gear>, <contenttweaker:infinite_chaos>, <contenttweaker:rak_coin>, <contenttweaker:quirk_gear>, <contenttweaker:rak_coin>, <contenttweaker:infinite_chaos>, <contenttweaker:taril_gear>, <contenttweaker:infinite_chaos>], 
	[<contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:rak_coin>, <contenttweaker:rak_coin>, <contenttweaker:rak_coin>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>, <contenttweaker:infinite_chaos>], 
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <ore:oc:materialALU>, <ore:oc:materialALU>, <ore:oc:materialALU>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:mat_plate>, <contenttweaker:prism_block>, <ore:oc:materialALU>, <contenttweaker:lew_plate>, <ore:oc:materialALU>, <contenttweaker:prism_block>, <contenttweaker:but_plate>, <contenttweaker:prism_block>], 
	[<contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <ore:oc:materialALU>, <ore:oc:materialALU>, <ore:oc:materialALU>, <contenttweaker:prism_block>, <contenttweaker:prism_block>, <contenttweaker:prism_block>]]);