name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f936474183b2a5d35b2d4ed76a2d8704a043802645e5226b8bfe7bbf35d89635"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
