name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f95f69c08c58ffbc7c487e98ff78ba46da8b722bc9c66a9a13d4d4fc22e1e826"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
