name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a086f4b7131dbf34580c518517c1b6e03aae5133e880865a6812961617b2db03"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
