name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1956c442da8509f4967dbcc74c1fd206db23c6c153eef5baab015ec21b2826f"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
