name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32a70d843eee8a0e7dff38eb3886654f15045cf9d86c1f837ee3fd1328e513d1"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
