name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f4c98185889c72167513ec0c729a219d962f3c1ea70cee59bab90e8b29d3aab"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
