name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d94a7a406ef1ba2892f03432349b428ff39eac69f537b1eb298c671fe764863c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
