name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4c4150f0304b7a5d108dcb24d5914dc580d37f045a2aa3255a0353a314aab69"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
