name = "toyvo_modpack"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58ea488054309193c24399eef042b0fc644a5c409e54272fea064c83bd54694d"

[versions]
forge = "50.1.19"
minecraft = "1.20.6"
