name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e25252989a0e22213251bad1b87c912f3d16b5d82611e1180fb133c40979ff5d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
