name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f6551d8014422360a1e05542ceaddafd5950bd3453c9e8db5f5483452b4c1fa"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
