name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a3edadf8cf95fec2095bf93cb05ff76c980b1f0c03414a81a2f9a58b89f1f61"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
