name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3a7c969340e49cda5b559259638dc611b0d31f750b9fc220d6eeb1be7fd6995"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
