name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a757dd1e66669f28a5c5de3ca5664969ba48d41ab52b98bcbfe8ceef38da4b70"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
