name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00e813dc7618a1544fd85f67016da028e6a0018d1acfe1bdc833b314ad0e9f24"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
