name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fb8d3d89f92081a1a2212b46df2db4b41c5a97d9a6d933ac4d9415b37f49c08"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
