name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce6fa2dd39697b138736511a946a3c6ccf8ca4a4ac3f99b913cfcdd2d875bf1a"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
