name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2720bc5f8dd38ed16027c6788d0e9ae9297f0c973ebb996b324e9ab3e17722d7"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
