name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec4d31f7b3168156451dbc107cb1525e177a91295d0a0f23a63f0384cd568455"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
