name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac45cad66f2e526998d186e539a8d208c487066594fc264e0a9c8d10ef2fd295"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
