name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cebe174bcb1882a0da312f2d77eddb1132ef3b3b32852b01a24cff42b312dae2"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
