name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaaddf2aecf14a9cb3c0e9197dc02ef36eed624a402cd07d4305747263ed3f12"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
