name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07eb5bbe6b819c06eafbea6250fac852fea500fcf5ae4af656ee640bbb26a150"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
