name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ad14b074d85c84b19f108cac28d9dddcb146f5e27d7870f08b7526a418ac7e0"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
