name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e279b0b05d88ea3e77962d71ec8c91c08df48db905146c5fdd42609b6bd2ad99"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
