name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10efd343c64bab409cad1b7c313de74c88c0f722e7d7b48094f5b5ca58d2d476"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
