name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a5af133abf03e16ff54779c806bbc5f4f139ac55ca6e187bee31a5a02a4c2f8"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
